// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/request.proto
package com.mdx.framework.server.api.base;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class Msg_Post extends Message {

  private static final long serialVersionUID = 1L;

  public static final String DEFAULT_NAME = "";
  public static final String DEFAULT_VALUE = "";

  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public String name;

  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public String value;

  public Msg_Post(String name, String value) {
    this.name = name==null?this.name:name;
    this.value = value==null?this.value:value;
  }

  public Msg_Post() {
  }

  private Msg_Post(Builder builder) {
    this(builder.name, builder.value);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Msg_Post)) return false;
    Msg_Post o = (Msg_Post) other;
    return equals(name, o.name)
        && equals(value, o.value);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = name != null ? name.hashCode() : 0;
      result = result * 37 + (value != null ? value.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Msg_Post> {
    private static final long serialVersionUID = 1L;


    public String name;
    public String value;

    public Builder() {
    }

    public Builder(Msg_Post message) {
      super(message);
      if (message == null) return;
      this.name = message.name;
      this.value = message.value;
    }

    @Override
    public Msg_Post build() {
      checkRequiredFields();
      return new Msg_Post(this);
    }
  }
}
